<a href="https://colab.research.google.com/github/vitria18/cars/blob/main/FirstProjectML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

#cars
url = "https://raw.githubusercontent.com/vitria18/cars/main/car.data"
cars = pd.read_csv(url)
cars.describe()

       vhigh vhigh.1     2   2.1 small   low  unacc
count   1727    1727  1727  1727  1727  1727   1727
unique     4       4     4     3     3     3      4
top     high    high     3     4   med   med  unacc
freq     432     432   432   576   576   576   1209